site_name: listless 💤
site_url: "https://listless.dev"
theme:
  name: material
  logo: assets/fatigue-light.svg
  favicon: assets/fatigue-dark.svg
  font:
    text: "Briskpace"
    code: "Mullet"
    # code: "Roboto Mono Medium"
  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
  # Setup for theme switch https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - tags
  - glightbox
  - placeholder:
      placeholder_file: placeholder-plugin.yaml
  - rss:
      match_path: .*

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - abbr
  - attr_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css

nav:
  - About: "index.md"
  - Techniques:
    - Pack two integers in one: "techniques/001-pack-two-integers-in-one.md"
    - Prefix/Suffix arrays: "techniques/002-prefix-suffix-arrays.md"
    - Converging pointers: "techniques/003-converging-pointers.md"
    - Seen map: "techniques/004-seen-map.md"
    - Sliding window: "techniques/005-sliding-window.md"
    - Fixed size heap: "techniques/006-fixed-size-heap.md"
  - Array:
    - Basic:
      - Remove duplicates: "array/001-remove-duplicates.md"
      - Generate all subsequences: "array/002-generate-all-subsequences.md"
      - Generate all subarrays: "array/003-generate-all-subarrays.md"
      - Rotate an array: "array/004-rotate-an-array.md"
      - Minimum operations to make elements equal: "array/005-minimum-operations-to-make-elements-equal.md"
    - Easy:
      - Contains duplicate within k distance: "array/006-contains-duplicate-within-k-distance.md"
      - Rearrange to make even positions greater than odds: "array/007-rearrange-to-make-even-positions-greater-than-odds.md"
      - Sum of all subarrays: "array/008-sum-of-all-subarrays.md"
      - Buy and sell stocks I: "array/009-buy-and-sell-stock-1.md"
      - Buy and sell stocks II: "array/010-buy-and-sell-stock-2.md"
      - Single among doubles: "array/011-unique-number.md"
      - Missing number in list of first N natural numbers: "array/012-missing-in-natural-numbers.md"
      - Repeating number in list of first N-1 natural numbers: "array/013-repeating-in-natural-numbers.md"
      - Missing and repeating number in list of first N natural numbers: "array/014-missing-and-repeating-in-natural-numbers.md"
      - Increasing triplets: "array/015-increasing-triplet.md"
      - Maximum sum subarray: "array/016-maximum-sum-subarray.md"
      - Equilibrium Index: "array/017-equilibrium-index.md"
      - Two sum: "array/018-two-sum.md"
      - Split array into equal sum segments: "array/019-split-array-into-equal-sum-segments.md"
      - Maximum consecutive ones after flipping zeros: "array/020-maximum-consecutive-ones.md"
    - Medium:
      - Rearrange array to be a<sub>i</sub> = i: "array/021-rearrange-to-be-ai-i.md"
      - Maximum sum circular subarray: "array/022-max-sum-circular-subarray.md"
      - Reorder by index array: "array/023-reorder-by-index-array.md"
      - Product of array except self: "array/024-product-of-array-except-self.md"
      - k-th largest subarray sum: "array/025-kth-largest-subarray-sum.md"
      - Smallest missing number in sorted array: "array/026-smallest-missing-in-sorted-array.md"
      - Shortest subarray with given sum: "array/027-shortest-subarray-with-given-sum.md"
