[project]
name = "site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-glightbox>=0.5.1",
    "mkdocs-material>=9.6.20",
    "mkdocs-placeholder-plugin>=0.5.1",
    "mkdocs-rss-plugin>=1.17.3",
]
